version: "3.8"

services:
  db:
    container_name: 'django_blog_example_db'
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "blog"
      POSTGRES_USER: "blog"
      POSTGRES_PASSWORD: "blog"
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: 'django_blog_example_data'